#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: v1
data:
  args-1: '--character-set-server=utf8mb4'
  args-2: '--collation-server=utf8mb4_bin'
  args-3: '--explicit-defaults-for-timestamp=1'
  args-4: '--datadir=/var/lib/mysql/data'
kind: ConfigMap
metadata:
  name: mysql-args-cm
---
apiVersion: v1
data:
  init.sql: grant all privileges on *.* to xwiki@'%'
kind: ConfigMap
metadata:
  name: mysql-init-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - 
          args:
            - $(MYSQL_ARG_1)
            - $(MYSQL_ARG_2)
            - $(MYSQL_ARG_3)
            - $(MYSQL_ARG_4)
          env:
            - 
              name: MYSQL_ARG_1
              valueFrom:
                configMapKeyRef:
                  key: args-1
                  name: mysql-args-cm
            - 
              name: MYSQL_ARG_2
              valueFrom:
                configMapKeyRef:
                  key: args-2
                  name: mysql-args-cm
            - 
              name: MYSQL_ARG_3
              valueFrom:
                configMapKeyRef:
                  key: args-3
                  name: mysql-args-cm
            - 
              name: MYSQL_ARG_4
              valueFrom:
                configMapKeyRef:
                  key: args-4
                  name: mysql-args-cm
            - 
              name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
            - 
              name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
            - 
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-secret
            - 
              name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
          image: mysql:5.7.32@sha256:ce6815027949d0b48e3097a94fa3ec062866a78868d50c7900c697c13574599f
          name: mysql-container
          ports:
            - 
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - 
              mountPath: /var/lib/mysql
              name: mysql-vol
            - 
              mountPath: /docker-entrypoint-initdb.d
              name: mysql-init-vol
      volumes:
        - 
          name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc
        - 
          configMap:
            name: mysql-init-cm
          name: mysql-init-vol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki-deploy
spec:
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
    spec:
      containers:
        - 
          env:
            - 
              name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_DATABASE
                  name: xwiki-secret
            - 
              name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: xwiki-secret
            - 
              name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: xwiki-secret
            - 
              name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: xwiki-secret
          image: openshiftacademiaonline/docker-xwiki-ops:1.0
          imagePullPolicy: Always
          name: xwiki-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - 
              mountPath: /usr/local/xwiki          
              name: xwiki-vol
      volumes:
        - 
          name: xwiki-vol
          persistentVolumeClaim:
            claimName: xwiki-pvc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-netpol
spec:
  ingress:
    - 
      from:
        - 
          podSelector:
            matchLabels:
              app: xwiki
      ports:
        - 
          port: 3306
  podSelector:
    matchLabels:
      app: mysql
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xwiki-netpol
spec:
  ingress:
    - 
      ports:
        - 
          port: 8080
  podSelector:
    matchLabels:
      app: xwiki
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /docker-xwiki/mysql-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xwiki-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /docker-xwiki/xwiki-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
stringData:
  MYSQL_DATABASE: xwiki
  MYSQL_PASSWORD: xwwiki
  MYSQL_ROOT_PASSWORD: xwiki
  MYSQL_USER: xwiki
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
---
apiVersion: v1
stringData:
  DB_DATABASE: xwiki
  DB_HOST: mysql-svc
  DB_PASSWORD: xwiki
  DB_USER: xwiki
kind: Secret
metadata:
  name: xwiki-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - 
      port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: xwiki-svc
spec:
  ports:
    - 
      nodePort: 30000
      port: 8080
  selector:
    app: xwiki
  type: NodePort
---
